# Generated by Django 5.2 on 2025-04-26 00:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FolderType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField()),
                ('cree_a', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.FileField(upload_to='pieces/')),
                ('fichier_taille', models.BigIntegerField()),
                ('piece_date', models.DateField()),
                ('date_televersement', models.DateTimeField(auto_now_add=True)),
                ('entite', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=50)),
                ('duree_vie', models.IntegerField()),
                ('est_public', models.BooleanField(default=False)),
                ('est_supprime', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('provenance', models.CharField(max_length=255)),
                ('importance', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('elevee', 'Élevée'), ('critique', 'Critique')], max_length=20)),
                ('dossier_date', models.DateField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('derniere_modification', models.DateTimeField(auto_now=True)),
                ('est_public', models.BooleanField(default=False)),
                ('est_supprime', models.BooleanField(default=False)),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.direction')),
                ('dossier_parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.foldertype')),
            ],
        ),
        migrations.CreateModel(
            name='FolderKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.folder')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.keyword')),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='keyword',
            field=models.ManyToManyField(through='core.FolderKeyword', to='core.keyword'),
        ),
        migrations.CreateModel(
            name='PieceKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.keyword')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.piece')),
            ],
        ),
        migrations.AddField(
            model_name='piece',
            name='keyword',
            field=models.ManyToManyField(through='core.PieceKeyword', to='core.keyword'),
        ),
        migrations.CreateModel(
            name='PieceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cree_a', models.CharField(max_length=255)),
                ('type_dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.foldertype')),
            ],
        ),
        migrations.AddField(
            model_name='piece',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.piecetype'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.direction')),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('est_occupe', models.BooleanField(default=False)),
                ('est_chef', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('attente', 'En attente'), ('desactive', 'Désactivé')], max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('poste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.poste')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrashItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('dossier', 'Dossier'), ('piece', 'Pièce')], max_length=50)),
                ('date_suppression', models.DateTimeField(auto_now_add=True)),
                ('justification', models.TextField(blank=True)),
                ('est_restauré', models.BooleanField(default=False)),
                ('date_restoration', models.DateTimeField(blank=True, null=True)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.folder')),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.piece')),
                ('restauré_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_restaures', to='core.user')),
                ('supprime_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_supprimes', to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='piecetype',
            name='createur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user'),
        ),
        migrations.CreateModel(
            name='PiecePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('peut_lire', models.BooleanField(default=False)),
                ('peut_editer', models.BooleanField(default=False)),
                ('peut_supprime', models.BooleanField(default=False)),
                ('attribution_date', models.DateTimeField(auto_now_add=True)),
                ('direction_beneficiaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.direction')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.piece')),
                ('structure_beneficiaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_piece', to='core.user')),
                ('donneur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piece_donnes', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='PieceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('consultation', 'Consultation')], max_length=50)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.piece')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='piece',
            name='createur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user'),
        ),
        migrations.AddField(
            model_name='foldertype',
            name='createur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user'),
        ),
        migrations.CreateModel(
            name='FolderPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('peut_lire', models.BooleanField(default=False)),
                ('peut_editer', models.BooleanField(default=False)),
                ('peut_supprime', models.BooleanField(default=False)),
                ('attribution_date', models.DateTimeField(auto_now_add=True)),
                ('direction_beneficiaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.direction')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.folder')),
                ('structure_beneficiaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_dossier', to='core.user')),
                ('donneur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossier_donnes', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='FolderHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('consultation', 'Consultation')], max_length=50)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.folder')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='createur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user'),
        ),
        migrations.CreateModel(
            name='ValidationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('attente', 'En attente'), ('desactive', 'Désactivé')], max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_demande', models.DateTimeField()),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='core.user')),
                ('valide_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='validation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.validationhistory'),
        ),
    ]
